# Generated by Django 3.1.3 on 2020-11-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anoletivo',
            name='ano',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='lotacao',
            constraint=models.UniqueConstraint(fields=('turma', 'professor', 'disciplina', 'ano_letivo'), name='conjunto turma-professor-disciplina-ano unico por lotação'),
        ),
    ]
